spring:
  application:
    name: account-payment-service
  profiles:
    active: {accountPaymentServiceProfile}

---

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${DATABASE_SCHEMA}
    hibernate:
#      ddl-auto: update
    show-sql: true
  datasource:
    url: ${DATABASE_HOST}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver

server:
  port: 8081
  servlet:
    context-path: /account_payment_service